force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Contact__c/Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC-{00000}</displayFormat>
        <label>Job Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobContactTriggerHandler.cls
public with sharing class JobContactTriggerHandler extends TriggerHandler {
    private List<Job_Contact__c> newJobContactList;

    public JobContactTriggerHandler() {
        this.newJobContactList = (List<Job_Contact__c>) Trigger.new;
    }

    public override void afterInsert() {
        setPrimaryContact(newJobContactList);
    }

    public override void afterUpdate() {
        setPrimaryContact(newJobContactList);
    }

    public static void setPrimaryContact(List<Job_Contact__c> jobContactList) {
        Map<Id, Job_Application__c> jobApplicationsById = new Map<Id, Job_Application__c>();

        for (Job_Contact__c jobContact : jobContactList) {
            if (jobContact.Primary_Contact__c == true) {
                jobApplicationsById.put(
                    jobContact.Job_Application__c,
                    new Job_Application__c(
                        Id = jobContact.Job_Application__c,
                        Primary_Contact__c = jobContact.Contact__c
                    )
                );
            }
        }

        if (!jobApplicationsById.isEmpty()) {
            update jobApplicationsById.values();
        }
    }
}