force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Contact__c/Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC-{00000}</displayFormat>
        <label>Job Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobContactTriggerHandler_Test.cls
@isTest
private with sharing class JobContactTriggerHandler_Test {
    @TestSetup
    public static void createData() {
        TestDataFactory.createJobContacts();
    }

    @isTest
    public static void testPrimaryContact() {
        Job_Contact__c jobContact = [
            SELECT Id, Contact__c, Job_Application__c, Primary_Contact__c
            FROM Job_Contact__c
            LIMIT 1
        ];

        Test.startTest();
        jobContact.Primary_Contact__c = true;
        update jobContact;
        Test.stopTest();

        Job_Application__c jobApp = [
            SELECT Id, Primary_Contact__c
            FROM Job_Application__c
            WHERE Id = :jobContact.Job_Application__c
        ];

        System.assertEquals(jobContact.Contact__c, jobApp.Primary_Contact__c, 'Wrong or missing Primary Contact'); 
    }

}