force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Contact__c/Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC-{00000}</displayFormat>
        <label>Job Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Contact__c/fields/Hiring_Role__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Role__c</fullName>
    <label>Hiring Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recruiter</fullName>
            </value>
            <value>
                <fullName>Recruiting Coordinator</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Peer Interviewer</fullName>
            </value>
            <value>
                <fullName>Executive Interviewer</fullName>
            </value>
            <value>
                <fullName>HR/People Partner</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Contact__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>Contact__r.Title</formula>
    <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {

    public static List<Account> createAccounts() {
        List<Account> accountList = new List<Account>();
        for (Integer i = 0; i < 10; i++) {
            Account account = new Account(
                Name = 'Test Account ' + i
            );
            accountList.add(account);
        }
        insert accountList;
        return accountList;
    }

    public static List<Contact> createContacts() {
        List<Account> accountList = createAccounts();
        List<Contact> contactList = new List<Contact>();
        for (Integer i = 0; i < accountList.size(); i++) {
            Contact contact = new Contact(
                AccountId = accountList[i].Id,
                FirstName = 'Test',
                LastName = 'Contact ' + i,
                Email = 'test.contact.' + i + '@example.com'
            );
            contactList.add(contact);
        }
        insert contactList;
        return contactList;
    }

    public static List<Job_Application__c> createJobApplications() {
        List<String> statuses = new List<String>{
            'Saved',
            'Applying',
            'Applied',
            'Interviewing',
            'Negotiating',
            'Accepted',
            'Closed',
            'Saved',
            'Applying',
            'Applied'
        };
        List<Account> accountList = createAccounts();
        List<Job_Application__c> jobApplicationList = new List<Job_Application__c>();
        for (Integer i = 0; i < statuses.size(); i++) {
            Job_Application__c jobApplication = new Job_Application__c(
                Company_Name__c = accountList[i].Id,
                Status__c = statuses[i],
                Title__c = 'Test Job ' + i
            );
            jobApplicationList.add(jobApplication);
        }
        insert jobApplicationList;
        return jobApplicationList;
    }
    
    public static List<Job_Contact__c> createJobContacts() {
        List<Contact> contactList = createContacts();
        List<Job_Application__c> jobApplicationList = createJobApplications();
        List<Job_Contact__c> jobContactList = new List<Job_Contact__c>();
        for (Integer i = 0; i < 10; i++) {
            Job_Contact__c jobContact = new Job_Contact__c(
                Contact__c = contactList[i].Id,
                Job_Application__c = jobApplicationList[i].Id,
                Hiring_Role__c = 'Recruiter'
            );
            jobContactList.add(jobContact);
        }
        insert jobContactList;
        return jobContactList;
    }

    public static List<Event> createEvents() {
        List<Job_Application__c> jobApplicationList = createJobApplications();
        Datetime firstStartTime = Datetime.newInstance(
            Date.today().addDays(1),
            Time.newInstance(10, 0, 0, 0)
        );

        List<Event> eventList = new List<Event>{
            new Event(
                Subject = 'Test Interview 1',
                StartDateTime = firstStartTime,
                EndDateTime = firstStartTime.addHours(1),
                Location = 'Test Location 1',
                WhatId = jobApplicationList[0].Id,
                OwnerId = UserInfo.getUserId()
            ),
            new Event(
                Subject = 'Test Interview 2',
                StartDateTime = firstStartTime.addHours(2),
                EndDateTime = firstStartTime.addHours(3),
                Location = 'Test Location 2',
                WhatId = jobApplicationList[1].Id,
                OwnerId = UserInfo.getUserId()
            )
        };
        insert eventList;
        return eventList;
    }

}